{% set name = "dwave-system" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-system-{{ version }}.tar.gz
  sha256: ff021e4d130612fe13914dc71b9168260f2cb5ab61485ca099a5f32bb6a30cdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dimod >=0.10.0,<0.13.0
    - dwave-cloud-client >=0.9.1,<0.11.0
    - dwave-networkx >=0.8.10
    - dwave-preprocessing >=0.3
    - dwave-tabu >=0.4.2
    - homebase >=1.0.0,<2.0.0
    - minorminer >=0.2.8,<0.3.0
    - networkx >=2.0,<3.0
    - numpy >=1.17.3,<2.0.0
    - python >=3.7
  run_constrained:
    - dwave-drivers >=0.4.0,<0.5.0

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-system
  summary: All things D-Wave System.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
