{% set name = "dwave-system" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-system-{{ version }}.tar.gz
  sha256: 112ea89a821eeadb704df69ac53dfeb993e422aa0f607e257766dc14d5f2dfd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dwave-samplers >=1.0.0
    - scipy >=1.7.3
    - dimod >=0.12.7,<0.14.0
    - dwave-cloud-client >=0.10.6,<0.12.0
    - dwave-networkx >=0.8.10
    - dwave-preprocessing >=0.5.0
    - homebase >=1.0.0,<2.0.0
    - minorminer >=0.2.8,<0.3.0
    - networkx >=2.0,<3.0
    - numpy >=1.20.0
    - python >=3.8
  run_constrained:
    - dwave-drivers >=0.4.0,<0.5.0

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-system
  summary: All things D-Wave System.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
